# Generated by Django 5.2.3 on 2025-06-28 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudProducto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(limit_choices_to={'stock__gt': 0}, on_delete=django.db.models.deletion.CASCADE, to='CrudProducto.producto')),
            ],
        ),
    ]
