# Generated by Django 5.2.3 on 2025-06-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudProducto', '0004_repartidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repartidor',
            name='disponible',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='Si', max_length=2, verbose_name='Disponibilidad'),
        ),
    ]
